image: node:latest

# 定义包含的阶段
stages:
  - build
  - test
  - deploy

# 缓存模块目录
# 加快处理速度
cache:
  paths:
    - node_modules/

# 准备工作
# 安装所有依赖模块
before_script:
  - chmod +x .autodevops/before.sh
  - .autodevops/before.sh
  - npm install
  
# binary
binary_test:
  stage: test
  allow_failure: true
  only:
    - merge_requests
  tags:
    - dev
  script:
    - npm run testing