image: node:latest

before_script:
  - npm install

service_cache_test:
  stage: test
  script:
    - node service/cache.js
  only:
  - master
  
service_core_test:
  stage: test
  script:
    - node service/core.js
  only:
  - master
  
service_device_test:
  stage: test
  script:
    - node service/device.js
  only:
  - master
  
service_disk_test:
  stage: test
  script:
    - node service/disk.js
  only:
  - master
  
service_interface_test:
  stage: test
  script:
    - node service/interface.js
  only:
  - master
  
service_media_test:
  stage: test
  script:
    - node service/media.js
  only:
  - master