# ==============
# 服务配置
# ==============

listen = 81
name = "water"
static = "./static"
debug = true


# ==============
# MongoDB配置
# ==============

[mongo]
host = "localhost"
port = 27017
db = "nursery"
collections = [
    "User",     # 用户表
    "Cup",       # 水杯表
    "UserCup",  # 用户水杯绑定表
]

# 数据库认证
# [mongo.auth]
# username = ""
# password = ""


# ==============
# Redis配置
# ==============

[redis]
host = "localhost"
port = 6379
password = "MGE1MTA0OGMzMzBkNjE4YzgwZDJiZTdhOGM4ZTI3MTMwOGJmZjZiOTJiYTFkZjhjZDY5YWE1NzQzOTkwMjc0Mm===="


# ==============
# RabbitMQ配置
# ==============

[rabbitmq]
host = "amqp://panda:panda@localhost"
topic = "bus"


# ==============
# 加密配置
# ==============

[crypto]
method = "aes256"
password = "ZDQxZTQ4OGM4MTg4ZDkYzljNjYIyNzcy"


# ==============
# 验证配置
# ==============

[schema]
status = true
code = "E.VALIDATE"


# ==============
# OSS配置
# ==============

[oss]