# ==============
# 服务配置
# ==============

listen = 81
name = "water"
static = "./static"


# ==============
# MongoDB配置
# ==============

[mongo]
host = "localhost"
port = 27017
db = "nursery"
collections = [
    "users",     # 用户表
    "cup",       # 水杯表
    "user_cup",  # 用户水杯绑定表
]

# 数据库认证
# [mongo.auth]
# username = ""
# password = ""


# ==============
# Redis配置
# ==============

[redis]
host = "localhost"
port = 6379
password = "MGE1MTA0OGMzMzBkNjE4YzgwZDJiZTdhOGM4ZTI3MTMwOGJmZjZiOTJiYTFkZjhjZDY5YWE1NzQzOTkwMjc0Mm===="


# ==============
# RabbitMQ配置
# ==============

[rabbitmq]
host = "amqp://panda:panda@localhost"
topic = "bus"


# ==============
# 加密配置
# ==============

[crypto]
method = "aes256"
password = "ZDQxZTQ4OGM4MTg4ZDkYzljNjYIyNzcy"


# ==============
# 日志配置
# ==============

[logs]
timeout = 86400000
path = "./logs"


# ==============
# 日志配置
# ==============

[oss]