[package]
name = "util"
version = "0.1.0"
authors = ["印盼 <xivistudios@gmail.com>"]
license = "MIT"
build = "build.rs"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "protocol"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.2.0"

[dependencies]
neon = "0.2.0"
rust-crypto = "^0.2"
base64 = "0.10.0"
toml = "0.4.10"
neon-serde = "0.1.1"
regex = "1"
chrono = "0.4"
lazy_static = "1.2.0"