# ==============
# 服务配置
# ==============

listen = 8089
name = "nursery.cache"


# ==============
# MongoDB配置
# ==============

[mongo]
host = "server.local"
port = 27017
db = "nursery"

# 数据库认证
[mongo.auth]
username = "nursery"
password = "6FlBWz4C4ScUb+UFNCLrGbveFk426Wa3Sh91aJRGhKQ="


# ==============
# Redis配置
# ==============

[redis]
host = "server.local"
port = 6379
password = "MGE1MTA0OGMzMzBkNjE4YzgwZDJiZTdhOGM4ZTI3MTMwOGJmZjZiOTJiYTFkZjhjZDY5YWE1NzQzOTkwMjc0Mm===="