# ==============
# 配置
# ==============

name = "nursery.core"


# ==============
# 服务配置
# ==============
[service]
nodeID = "core"
transporter = "nats://server.local:4222"
logLevel = "info"
requestTimeout = 5000


# ==============
# MongoDB配置
# ==============

[mongo]
host = "server.local"
port = 27017
db = "nursery"

# 数据库认证
[mongo.auth]
username = "nursery"
password = "6FlBWz4C4ScUb+UFNCLrGbveFk426Wa3Sh91aJRGhKQ="