# ==============
# 服务配置
# ==============

listen = 8082
name = "nursery.disk"
debug = true


# ==============
# 存储配置
# ==============

[stage]
path = "/mnt/d/project/nursery/AppData"


# ==============
# MongoDB配置
# ==============

[mongo]
host = "server.local"
port = 27017
db = "nursery"

# 数据库认证
[mongo.auth]
username = "nursery"
password = "6FlBWz4C4ScUb+UFNCLrGbveFk426Wa3Sh91aJRGhKQ="


# ==============
# ELK配置
# ==============

[elk]
node = "http://elk.server.local:9200"
maxRetries = 3
requestTimeout = 10000
name = "nursery.disk"


# ==============
# RabbitMQ配置
# ==============

[rabbitmq]
host = "amqp://nursery:MTMwOGJmZjZiOTJiYTFkZjh@server.local"
prefetch = 1