# ==============
# 服务配置
# ==============

listen = 8082
name = "nursery.disk"
debug = true


# ==============
# 存储配置
# ==============

[stage]
path = "D:/project/nursery/static"


# ==============
# ELK配置
# ==============

[elk]
node = "http://elk.server.local:9200"
maxRetries = 3
requestTimeout = 10000
name = "nursery.interface"