# ==============
# 配置
# ==============

listen = 8080
name = "nursery.interface"
debug = true


# ==============
# 服务配置
# ==============

[service]
nodeID = "interface"
transporter = "nats://server.local:4222"
logLevel = "info"
requestTimeout = 5000

# 服务注册配置
[service.registry]
strategy = "RoundRobin"


# ==============
# 缓存配置
# ==============

[cache]
host = "localhost"
port = 8089


# ==============
# MongoDB配置
# ==============

[mongo]
host = "server.local"
port = 27017
db = "nursery"

# 数据库认证
[mongo.auth]
username = "nursery"
password = "6FlBWz4C4ScUb+UFNCLrGbveFk426Wa3Sh91aJRGhKQ="


# ==============
# Redis配置
# ==============

[redis]
host = "server.local"
port = 6379
password = "MGE1MTA0OGMzMzBkNjE4YzgwZDJiZTdhOGM4ZTI3MTMwOGJmZjZiOTJiYTFkZjhjZDY5YWE1NzQzOTkwMjc0Mm===="


# ==============
# 加密配置
# ==============

[crypto]
method = "aes256"
password = "ZDQxZTQ4OGM4MTg4ZDkYzljNjYIyNzcy"


# ==============
# 验证配置
# ==============

[schema]
status = true
code = "E.PARAMS.TYPE"


# ==============
# ELK配置
# ==============

[elk]
node = "http://elk.server.local:9200"
maxRetries = 3
requestTimeout = 10000
name = "nursery.interface"