# ==============
# 服务配置
# ==============

name = "nursery.media"


# ==============
# 服务配置
# ==============

[service]
nodeID = "media"
transporter = "nats://server.local:4222"
logLevel = "info"
requestTimeout = 5000

# 服务注册配置
[service.registry]
strategy = "RoundRobin"


# ==============
# 存储配置
# ==============

[stage]
path = "/mnt/d/project/nursery/AppData"
size = 280


# ==============
# MongoDB配置
# ==============

[mongo]
host = "server.local"
port = 27017
db = "nursery"

# 数据库认证
[mongo.auth]
username = "nursery"
password = "6FlBWz4C4ScUb+UFNCLrGbveFk426Wa3Sh91aJRGhKQ="